/**
 * patch-seed.mjs
 * Updates all imageUrl values in seed-firebase.mjs with unique keyword-based Unsplash URLs.
 */
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const seedPath = resolve(__dirname, "seed-firebase.mjs");
let content = readFileSync(seedPath, "utf-8");

const u = (kw) => `https://source.unsplash.com/400x300/?${encodeURIComponent(kw)}`;

const IMAGE_MAP = {
  "Pav Bhaji": u("pav bhaji indian street food butter spicy"),
  "Dahi Bhalle": u("dahi bhalle yogurt lentil dumpling chaat"),
  "Bhalla Papdi": u("papdi chaat crispy indian snack tamarind"),
  "Jaljeera (Extra 150ml)": u("jaljeera spiced cumin water indian cooler drink"),
  "Stuff Golgappa (Dahi Wala)": u("golgappa pani puri indian street food dahi"),
  "Chatpata Suka Golgappa": u("dry golgappa puri crispy masala spicy snack"),
  "Chatpata Cream Golgappa": u("cream golgappa chaat chatpata yogurt"),
  "Chilli Garlic Potato": u("chilli garlic potato crispy fried snack"),
  "Spring Roll (Noodles)": u("spring roll fried golden noodle chinese"),
  "Cheese Corn Roll": u("cheese corn roll fried crispy golden snack"),
  "Manchurian Dry": u("manchurian dry veg balls indo chinese spicy"),
  "Manchurian Gravy": u("manchurian gravy sauce chinese indian bowl"),
  "Manchurian Hongkong": u("hongkong chinese stir fry aromatic sauce"),
  "Cheese Manchurian": u("cheese manchurian melted gooey chinese food"),
  "Cheese Chilli Dry": u("chilli paneer dry spicy pepper chinese snack"),
  "Cheese Chilli Gravy": u("chilli cheese gravy sauce chinese food"),
  "Cheese Finger": u("cheese sticks fingers fried crispy golden"),
  "Mushroom Chilli Dry": u("mushroom chilli dry stir fry garlic"),
  "Mushroom Chilli Gravy": u("mushroom chilli gravy spicy sauce"),
  "Mushroom Duplex": u("mushroom sauteed garlic butter sauce"),
  "Crispy Veg.": u("crispy battered fried mixed vegetables"),
  "Veg. Bullets": u("vegetable balls fried spicy tangy snack"),
  "Paneer Singapuri": u("paneer singapore style coconut spice"),
  "Paneer Hongkong": u("paneer stir fry sweet spicy chinese glaze"),
  "Honey Chilli Potato": u("honey chilli potato sweet spicy crispy"),
  "Honey Chilly Cauliflower": u("honey chilli cauliflower glazed crispy"),
  "Margherita Pizza": u("margherita pizza tomato mozzarella basil"),
  "Mix Veg Pizza": u("vegetable pizza colorful bell pepper onion"),
  "Mix Veg Corn Pizza": u("corn vegetable pizza sweet corn topping cheese"),
  "Sweet Corn Pizza": u("sweet corn cheese pizza slice baked"),
  "Achari Pizza": u("spiced indian pizza pickle masala topping"),
  "Tandoori Pizza": u("tandoori pizza grilled smoky indian spiced"),
  "Mexican Pizza": u("mexican pizza jalapeno bell pepper salsa"),
  "Double Cheese Pizza": u("double cheese pizza mozzarella stretch pull"),
  "Chilly Paneer Pizza": u("paneer chilli pizza fusion spicy indian"),
  "Paneer Tikka Pizza": u("paneer tikka pizza grilled smoky indian"),
  "Makhani Paneer Pizza": u("makhani butter paneer pizza creamy sauce"),
  "Red Sauce Juicy Pasta": u("red sauce arrabbiata pasta tomato herb"),
  "Spl. Red Sauce Juicy Pasta": u("special red sauce pasta loaded vegetables"),
  "White Sauce Pasta": u("white cream sauce pasta bechamel creamy"),
  "Spl. White Sauce Pasta": u("creamy white sauce pasta premium rich"),
  "Mix Sauce Pasta": u("pasta red white mixed sauce creamy tomato"),
  "Veg. Manchow Soup": u("manchow soup noodles chinese vegetable bowl"),
  "Veg. Sweet Corn Soup": u("sweet corn soup creamy warm bowl"),
  "Veg Hot & Sour Soup": u("hot sour soup chinese spicy tangy tofu"),
  "Veg. Noodles": u("vegetable noodles stir fry indo chinese"),
  "Veg. Chilli Garlic Noodles": u("chilli garlic noodles spicy stir fry"),
  "Veg. Singapuri Noodles": u("singapore noodles thin rice spiced"),
  "Hakka Noodles": u("hakka noodles wok tossed vegetables"),
  "Veg. Noodles Chopsuey": u("chopsuey crispy noodles sauce stir fry"),
  "Spanish Noodles": u("spanish noodles pepper colorful sauce"),
  "Special Noodles": u("special chef noodles sauce premium stir fry"),
  "Veg. Fried Rice": u("vegetable fried rice wok basmati soy"),
  "Veg. Garlic Chilli Fried Rice": u("garlic chilli fried rice spicy bold"),
  "Manchurian with Fried Rice": u("manchurian fried rice combo chinese plate"),
  "Cheese Chilly Fried Rice": u("cheese chilli fried rice melted spicy"),
  "Plain Dosa": u("plain dosa crispy thin rice crepe south indian"),
  "Masala Dosa": u("masala dosa potato stuffed crispy south indian"),
  "Veg. Dosa": u("vegetable dosa stuffed colorful south indian"),
  "Onion Dosa": u("onion dosa caramelized crispy south indian"),
  "Paneer Dosa": u("paneer dosa stuffed cottage cheese south indian"),
  "Spl. Dosa": u("special dosa chef signature crispy south indian"),
  "Masala Rava Dosa": u("rava semolina masala dosa crispy light"),
  "Onion Rava Dosa": u("onion rava dosa thin crispy semolina"),
  "Paneer Rava Dosa": u("paneer rava semolina dosa stuffed crispy"),
  "Masala Uttapam": u("masala uttapam thick rice pancake vegetables"),
  "Onion Uttapam": u("onion uttapam soft pancake south indian"),
  "Paneer Uttapam": u("paneer uttapam thick soft rice pancake"),
  "Idli Sambar": u("idli sambar steamed rice cake lentil soup"),
  "Vada Sambar": u("medu vada sambar crispy lentil donut south indian"),
  "Dahi Vada": u("dahi vada yogurt lentil dumpling sweet chutney"),
  "Veg. Biryani": u("vegetable biryani aromatic basmati spices"),
  "Veg Biryani Gravy": u("veg biryani gravy curry rice aromatic"),
  "Spl. Biryani": u("special biryani chef signature rice spiced"),
  "Mutter Pullao": u("mutter peas pulao basmati rice fragrant"),
  "Jeera Rice": u("jeera rice cumin basmati steamed ghee"),
  "Dal Makhani": u("dal makhani black lentil butter cream punjabi"),
  "Dal Yellow": u("yellow dal lentil tadka turmeric bowl"),
  "Dal Punjabi Tadka": u("punjabi dal tadka ghee spice sizzling"),
  "Chana Masala": u("chana masala chickpea curry spiced tomato"),
  "Mix Vegetable": u("mix vegetable curry indian gravy seasonal"),
  "Nav Ratan Korma": u("navratan korma nine vegetable korma cream nuts"),
  "Mushroom Mutter": u("mushroom mutter peas curry tomato gravy"),
  "Mushroom Do Piaza": u("mushroom do pyaza double onion gravy"),
  "Malai Kofta": u("malai kofta paneer potato dumpling cream gravy"),
  "Malai Methi": u("malai methi fenugreek cream curry"),
  "Cheese Tomato": u("cheese tomato curry melted indian"),
  "Shahi Paneer": u("shahi paneer royal cream cashew gravy indian"),
  "Palak Paneer": u("palak paneer spinach cottage cheese green curry"),
  "Paneer Lababdar": u("paneer lababdar tomato onion spiced gravy"),
  "Paneer Do Piaza": u("paneer do pyaza double onion caramelized"),
  "Karahi Paneer": u("karahi paneer iron wok tomato pepper spiced"),
  "Paneer Kofta": u("paneer kofta fried dumpling cream gravy"),
  "Paneer Butter Masala": u("paneer butter masala makhani cream tomato"),
  "Paneer Pasanda Masala": u("paneer pasanda stuffed mughlai nutty gravy"),
  "Rara Paneer": u("rara paneer thick punjabi robust gravy"),
  "Handi Paneer": u("handi paneer clay pot slow cooked smoky"),
  "Paneer Khurchan": u("paneer khurchan shredded stir fry dry masala"),
  "Makhani Paneer": u("makhani paneer butter rich creamy tomato"),
  "Delhi Spl. Paneer Begam Bar": u("paneer begam bar royal signature delhi special"),
  "Plain Roti": u("plain roti tandoor wheat bread indian"),
  "Butter Roti": u("butter roti tandoor fresh wheat melted butter"),
  "Naan": u("naan bread tandoor leavened soft pillowy"),
  "Missi Roti": u("missi roti chickpea flour herb spiced flatbread"),
  "Garlic Naan": u("garlic naan tandoor minced garlic butter fragrant"),
  "Butter Naan": u("butter naan fluffy golden tandoor"),
  "Cheese Naan": u("cheese naan stuffed melted gooey bread"),
  "Pudina Prantha": u("pudina mint paratha flaky layered fresh"),
  "Laccha Prantha": u("laccha paratha multi layer crispy flaky"),
  "Red/Green Chilli Prantha": u("chilli stuffed paratha spicy flatbread"),
  "Paneer Tikka": u("paneer tikka tandoor grilled smoky marinated"),
  "Paneer Malai": u("paneer malai tikka cream marinated grilled soft"),
  "Mushroom Tikka": u("mushroom tikka tandoor grilled marinated yogurt"),
  "Mushroom Malai Tikka": u("mushroom malai tikka cream rich grilled"),
  "Snacks Champ (Dry)": u("soya champ grilled dry spiced tandoor"),
  "Masala Champ": u("masala champ soya vibrant spiced grilled"),
  "Malai Champ": u("malai champ cream cheese soya grilled soft"),
  "Aachari Champ": u("achari champ pickle spiced soya tandoor"),
  "Kalimirch Champ": u("black pepper champ soya grilled bold"),
  "Afgani Champ": u("afghani champ cream cashew cardamom grilled"),
  "Mint Haryali Champ": u("haryali mint green coriander soya grilled"),
  "Butter Masala Gravy Champ": u("butter masala gravy soya champ rich"),
  "Delhi Spl. Champ": u("delhi special soya champ signature house"),
  "Delhi Spl. Gravy Champ": u("delhi special champ secret gravy house"),
  "White Gravy Champ": u("white gravy soya champ cream mild"),
  "Veg Wrap": u("vegetable wrap kathi roll paratha spiced"),
  "Chilli Paneer Wrap": u("chilli paneer wrap spicy roll paratha"),
  "Paneer Tikka Wrap": u("paneer tikka wrap kathi roll smoky mint"),
  "Aloo Tikki Burger": u("aloo tikki burger potato patty indian bun"),
  "Crispy Chatpta Burger": u("crispy chatpata burger tangy patty bun"),
  "Veggie Burger": u("veggie burger fresh vegetable patty lettuce"),
  "Noodle Burger": u("noodle burger crispy indo chinese fusion"),
  "Mexican Burger": u("mexican burger jalapeno salsa spicy bun"),
  "Tandoori Burger": u("tandoori burger smoky spiced sesame bun"),
  "Cheese Slice Burger": u("cheese slice burger melted american classic"),
  "Cheese Bust Burger": u("cheese burst burger oozing melted inside"),
  "Makhani Burger": u("makhani butter burger rich sauce brioche"),
  "Spicy Garlic Burger": u("spicy garlic burger mayo bold crispy"),
  "Maharaja Burger": u("maharaja burger double patty loaded tall"),
  "French Fries Plain": u("french fries golden crispy salted potato"),
  "French Fries Peri-Peri": u("peri peri fries spicy seasoning crispy"),
  "French Fries with Cheese": u("cheese fries loaded sauce melted crispy"),
  "French Fries Smokey": u("smokey bbq fries seasoned crispy golden"),
  "Veg Grilled Sandwich": u("grilled vegetable sandwich pressed toasted"),
  "Veg Corn Sandwich": u("corn vegetable sandwich grilled creamy"),
  "Tandoori Sandwich": u("tandoori vegetable sandwich smoky desi"),
  "Mexican Sandwich": u("mexican sandwich salsa pepper zesty grilled"),
  "Chilly Paneer Sandwich": u("chilli paneer sandwich grilled spicy"),
  "Paneer Tikka Sandwich": u("paneer tikka sandwich grilled mint chutney"),
  "Stuffed Garlic Bread": u("stuffed garlic bread cheese vegetable toasted"),
  "Stuffed Mushroom Garlic Bread": u("mushroom garlic bread stuffed cheese sauteed"),
  "Spicy Paneer Garlic Bread": u("paneer garlic bread spicy masala cheese"),
  "Veg. Steam Momos": u("steamed veg momos dumplings healthy light"),
  "Fried Momos": u("fried momos crispy golden dumplings"),
  "Tandoori Momos": u("tandoori momos grilled smoky spiced"),
  "Pineapple Raita": u("pineapple raita yogurt tropical sweet"),
  "Mix Veg Raita": u("mix vegetable raita yogurt cooling indian"),
  "Boondi Raita": u("boondi raita crispy pearls yogurt cumin"),
  "Green Salad": u("green salad fresh cucumber tomato onion lemon"),
  "Papad": u("papad roasted crispy indian accompaniment"),
  "Fresh Lime Soda": u("fresh lime soda sparkling citrus drink"),
  "Mojito (Mocktail)": u("mojito mocktail mint lime sparkling fresh"),
  "Black Current Mojito": u("blackcurrant mojito purple berry mocktail"),
  "Peach Mojito": u("peach mojito fruity aromatic mocktail"),
  "Blue Sky (Mocktail)": u("blue mocktail tropical citrus vivid drink"),
  "Jungle Bird (Mocktail)": u("jungle bird tropical fruit mocktail exotic"),
  "Sunsets (Mocktail)": u("sunset mocktail orange berry gradient drink"),
  "Thai Beach (Mocktail)": u("thai beach coconut lychee tropical mocktail"),
  "Cappuccino": u("cappuccino espresso milk foam coffee latte art"),
  "Americano": u("americano black coffee bold espresso"),
  "Green Tea": u("green tea cup healthy antioxidant"),
  "Masala Tea": u("masala chai indian spiced tea ginger cardamom"),
  "Packed Water": u("mineral water bottle refreshing"),
  "Soft Drink": u("soft drink carbonated cola chilled"),
  "Ice Cream (Regular)": u("ice cream scoop vanilla creamy dessert"),
  "Ice Cream (Premium)": u("premium ice cream scoop rich creamy waffle cone"),
  "Cold Coffee": u("cold coffee blended iced milk chilled"),
  "Vanilla Shakes": u("vanilla milkshake thick creamy smooth white"),
  "Strawberry Shakes": u("strawberry milkshake pink thick fruity"),
  "Mango Shakes": u("mango milkshake thick yellow tropical"),
  "Black Current Shakes": u("blackcurrant milkshake purple berry thick"),
  "Chocolate Shakes": u("chocolate milkshake dark cocoa thick creamy"),
  "Orio Shakes": u("oreo milkshake cookie cream thick"),
  "Kitkat Shakes": u("kitkat chocolate wafer milkshake"),
  "Butter Scotch Shakes": u("butterscotch milkshake caramel golden thick"),
};

let updated = 0;

// For each item name, find its block and replace the imageUrl line
for (const [name, url] of Object.entries(IMAGE_MAP)) {
  // Escape special regex chars in name
  const esc = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  // Match: name line, then any content, then imageUrl: img("..."), capturing prefix
  const rx = new RegExp(
    `(name:\\s*"${esc}",[\\s\\S]{0,300}?imageUrl:\\s*)img\\("[^"]*"\\)`,
    "g"
  );
  const next = content.replace(rx, (_, prefix) => {
    updated++;
    return `${prefix}"${url}"`;
  });
  if (next !== content) content = next;
}

writeFileSync(seedPath, content, "utf-8");
console.log(`✅ Patched ${updated} imageUrl entries in seed-firebase.mjs`);
